; ---------------------------------------------------------------------------
; fpga.inc
; handy info about locations in the FPGA
; 03-04-19 E. Brombaugh
; ---------------------------------------------------------------------------

.define   GPIO_DATA $1000    ;  GPIO data register location
.define   ACIA_CTRL $2000    ;  ACIA control register location
.define   ACIA_DATA $2001    ;  ACIA data register location
.define   USB_CTRL  $3000    ;  USB control register location
.define   USB_DATA  $3001    ;  USB data register location

